apiVersion: v1
kind: Secret

metadata:
  name: app-secrets
  namespace: ecommerce

type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.secrets.internalServiceToken }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoUsername }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoPassword }}
