apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service-depl
  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.orderService.replicaCount }}

  selector:
    matchLabels:
      app: order-service-app

  template:
    metadata:
      labels:
        app: order-service-app

    spec:
      containers:
        - name: order-service
          image: {{ .Values.orderService.image.repository}}:{{ .Values.orderService.image.tag }}
          imagePullPolicy: {{ .Values.orderService.image.imagepullPolicy }}
          ports:
            - containerPort: {{ .Values.orderService.service.targetPort }}

          envFrom:
            - configMapRef:
                name: order-service-configmap

            - secretRef:
                name: app-secrets
