apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service-depl
  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.paymentService.replicaCount }}

  selector:
    matchLabels:
      app: payment-service-app

  template:
    metadata:
      labels:
        app: payment-service-app

    spec:
      containers:
        - name: payment-service
          image: {{ .Values.paymentService.image.repository }}:{{ .Values.paymentService.image.tag }}
          imagePullPolicy: {{ .Values.paymentService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.paymentService.service.targetPort }}

          envFrom:
            - configMapRef:
                name: payment-service-configmap
            - secretRef:
                name: app-secrets
