apiVersion: v1
kind: Secret

metadata:
  name: app-secrets
  namespace: ecommerce

type: Opaque
stringData:
  JWT_SECRET: your_super_secret_jwt_key_change_in_production
  INTERNAL_SERVICE_TOKEN: internal_service_token_change_in_production
  MONGO_ROOT_PASSWORD: secret123
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: secret123
