apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway-depl
  namespace: {{ .Values.namespace }}

spec:

  replicas: {{ .Values.apiGateway.replicaCount }}

  selector:
    matchLabels:
      app: api-gateway-app

  template:
    metadata:
      labels:
        app: api-gateway-app

    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.apiGateway.service.targetPort }}

          envFrom:
            - configMapRef:
                name: api-gateway-configmap

            - secretRef:
                name: app-secrets
