apiVersion: v1
kind: ConfigMap

metadata:
  name: user-service-configmap
  namespace: ecommerce

data:
  PORT: "3001"
  MONGO_URI: mongodb://admin:secret123@mongodb:27017/userdb?authSource=admin
  JWT_EXPIRES_IN: 7d
  NODE_ENV: development
