apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service-depl
  namespace: {{ .Values.namespace}}

spec:

  replicas: {{ .Values.productService.replicaCount }}

  selector:
    matchLabels:
      app: product-service-app

  template:
    metadata:
      labels:
        app: product-service-app

    spec:
      containers:
        - name: product-service
          image: {{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}
          imagePullPolicy: {{ .Values.productService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.productService.service.targetPort }}

          envFrom:
            - configMapRef:
                name: product-service-configmap

            - secretRef:
                name: app-secrets      
